GET http://localhost:8080/api/v1/entidades HTTP/1.1

###

GET http://localhost:8080/api/v1/entidades/1 HTTP/1.1

###

POST http://localhost:8080/api/v1/entidades HTTP/1.1
content-type: application/json

{
    "nome": "Samuel",
    "dtNascimento": "Wed, 21 Oct 2015 18:27:50 GMT"
}


###

DELETE http://localhost:8080/api/v1/entidades/1 HTTP/1.1


###

PUT http://localhost:8080/api/v1/entidades HTTP/1.1
content-type: application/json

{
    "id": 1,
    "nome": "Samuel Silva",
    "dtNascimento": "Wed, 21 Oct 2015 18:27:50 GMT"
}